# =========================================================
# Workflow Manager
# Autonomous AI DBA Operations Platform
# =========================================================

# =========================================================
# IMPORTS
# =========================================================

from app.common.environment_validator import (
    validate_environment
)

from app.mcp_server.monitoring_executor import (
    execute_monitoring
)

from app.mcp_server.ai_executor import (
    run_ai_analysis
)

from app.mcp_server.report_executor import (
    save_report
)

from app.mcp_server.notification_executor import (
    run_notifications
)

from app.repository.incident_repository import (
    save_incident
)

from app.governance.governance_executor import (
    create_governance_request
)

from app.audit.audit_logger import (
    write_audit_log
)

from app.common.error_handler import (
    handle_error
)

from app.ai_agent.agent_executor import (
    execute_agent_workflow
)

from app.notifications.notification_router import (
    get_notification_route
)

from app.ai_agent.sql_action_executor import (
    generate_sql_action
)

from app.ai_agent.sql_risk_analyzer import (
    analyze_sql_risk
)

from app.ai_agent.sql_validator import (
    validate_sql_action
)

from app.ai_agent.sql_executor import (
    execute_sql_action
)

from app.repository.action_repository import (
    save_action
)

from app.ai_agent.execution_verifier import (
    verify_execution
)

from app.ai_agent.remediation_executor import (
    execute_remediation
)


# =========================================================
# WORKFLOW STEPS
# =========================================================

WORKFLOW_STEPS = [
    "Environment Validation",
    "Run Monitoring Engine",
    "Collect Monitoring Results",
    "Send Incident To AI Agent",
    "Agent Risk Assessment",
    "Agent Recommendation",
    "SQL Action Generation",
    "SQL Risk Analysis",
    "SQL Validation",
    "Governance Review",
    "SQL Execution",
    "Execution Verification",
    "Remediation Execution",
    "Generate RCA Report",
    "Save Incident To Repository",
    "Send Notifications",
    "Save Incident Report"
]


# =========================================================
# DISPLAY WORKFLOW
# =========================================================

def display_workflow_steps():
    """
    Display workflow execution steps.
    """

    print("\n========================================")
    print(" MCP WORKFLOW EXECUTION ")
    print("========================================\n")

    for step_number, step in enumerate(
        WORKFLOW_STEPS,
        start=0
    ):
        print(
            f"{step_number}. {step}"
        )


# =========================================================
# SAFE AI RESULT BUILDER
# =========================================================

def build_safe_ai_result(
    ai_result
):
    """
    Build safe AI result if AI service fails or returns invalid format.
    """

    if not isinstance(
        ai_result,
        dict
    ):
        return {
            "status": "FALLBACK",
            "analysis": {
                "summary": "AI analysis unavailable. Fallback analysis generated by workflow manager.",
                "root_cause": "AI service returned an invalid response.",
                "recommendation": "Continue monitoring and review SQL health manually.",
                "severity": "LOW"
            }
        }

    if ai_result.get(
        "status"
    ) == "FAILED":
        return {
            "status": "FALLBACK",
            "analysis": {
                "summary": "AI analysis unavailable due to AI gateway error.",
                "root_cause": ai_result.get(
                    "error",
                    "AI gateway error"
                ),
                "recommendation": "Continue monitoring and review SQL health manually.",
                "severity": "LOW"
            }
        }

    if not isinstance(
        ai_result.get(
            "analysis"
        ),
        dict
    ):
        return {
            "status": "FALLBACK",
            "analysis": {
                "summary": str(
                    ai_result.get(
                        "analysis",
                        "AI analysis unavailable."
                    )
                ),
                "root_cause": "AI analysis response was not structured.",
                "recommendation": "Continue monitoring and review SQL health manually.",
                "severity": "LOW"
            }
        }

    return ai_result


# =========================================================
# EXECUTE WORKFLOW
# =========================================================

def execute_workflow():
    """
    Execute complete MCP workflow.
    """

    try:

        # =================================================
        # WORKFLOW START
        # =================================================

        write_audit_log(
            "WORKFLOW STARTED"
        )

        print("\n========================================")
        print(" EXECUTING MCP WORKFLOW ")
        print("========================================\n")

        approval_request = None
        sql_action = None
        sql_risk = None
        validation_result = None
        execution_result = None
        verification_result = None
        remediation_result = None

        notification_route = {
            "send_email": False,
            "send_teams": False,
            "escalation_required": False
        }

        # =================================================
        # STEP 0 - ENVIRONMENT VALIDATION
        # =================================================

        write_audit_log(
            "STEP 0 STARTED - Environment Validation"
        )

        print(
            "[STEP 0] Environment Validation"
        )

        validate_environment()

        write_audit_log(
            "STEP 0 COMPLETED - Environment Validation"
        )

        # =================================================
        # STEP 1 - MONITORING
        # =================================================

        write_audit_log(
            "STEP 1 STARTED - Monitoring Engine"
        )

        print(
            "\n[STEP 1] Run Monitoring Engine"
        )

        monitoring_result = execute_monitoring()

        write_audit_log(
            "STEP 1 COMPLETED - Monitoring Engine"
        )

        # =================================================
        # STEP 2 - COLLECT RESULTS
        # =================================================

        write_audit_log(
            "STEP 2 STARTED - Collect Monitoring Results"
        )

        print(
            "\n[STEP 2] Collect Monitoring Results"
        )

        print(
            "Monitoring results collected successfully."
        )

        write_audit_log(
            "STEP 2 COMPLETED - Collect Monitoring Results"
        )

        # =================================================
        # STEP 3 - AI ANALYSIS
        # =================================================

        write_audit_log(
            "STEP 3 STARTED - AI Analysis"
        )

        print(
            "\n[STEP 3] Send Incident To AI Agent"
        )

        ai_result = run_ai_analysis(
            monitoring_result[
                "incident_summary"
            ]
        )

        ai_result = build_safe_ai_result(
            ai_result
        )

        write_audit_log(
            f"AI RESULT STATUS: {ai_result.get('status')}"
        )

        # =================================================
        # STEP 3A - AGENT EXECUTION
        # =================================================

        write_audit_log(
            "STEP 3A STARTED - Agent Execution"
        )

        print(
            "\n[STEP 3A] Agent Risk Assessment"
        )

        agent_intent_result = {
            "intent": "DAILY_HEALTH_CHECK",
            "confidence": 95,
            "source": "MCP_WORKFLOW_MANAGER"
        }

        agent_result = execute_agent_workflow(
            monitoring_result,
            agent_intent_result,
            ai_result[
                "analysis"
            ]
        )

        notification_route = get_notification_route(
            agent_result[
                "risk"
            ][
                "severity"
            ]
        )

        print(
            "\nNotification Route:\n"
        )

        print(
            notification_route
        )

        print(
            "\nAgent Risk:\n"
        )

        print(
            agent_result[
                "risk"
            ]
        )

        print(
            "\nAgent Recommendation:\n"
        )

        print(
            agent_result[
                "recommendation"
            ][
                "recommendation"
            ]
        )

        save_action(
            "RISK_CLASSIFICATION",
            "RISK CLASSIFIER",
            "SUCCESS",
            agent_result[
                "risk"
            ][
                "severity"
            ]
        )

        save_action(
            "RECOMMENDATION",
            "RECOMMENDATION ENGINE",
            "SUCCESS",
            agent_result[
                "recommendation"
            ][
                "recommendation"
            ]
        )

        write_audit_log(
            f"AGENT RISK: {agent_result['risk']['severity']}"
        )

        write_audit_log(
            f"AGENT RECOMMENDATION: {agent_result['recommendation']['recommendation']}"
        )

        write_audit_log(
            "STEP 3A COMPLETED - Agent Execution"
        )

        write_audit_log(
            "STEP 3 COMPLETED - AI Analysis"
        )

        # =================================================
        # STEP 3B - SQL ACTION GENERATION
        # =================================================

        write_audit_log(
            "STEP 3B STARTED - SQL Action Generation"
        )

        print(
            "\n[STEP 3B] SQL Action Generation"
        )

        sql_action = generate_sql_action(
            agent_result[
                "recommendation"
            ]
        )

        print(
            "\nGenerated SQL Action:\n"
        )

        print(
            sql_action
        )

        write_audit_log(
            f"SQL ACTION: {sql_action['action_type']}"
        )

        write_audit_log(
            "STEP 3B COMPLETED - SQL Action Generation"
        )

        # =================================================
        # STEP 3C - SQL RISK ANALYSIS
        # =================================================

        write_audit_log(
            "STEP 3C STARTED - SQL Risk Analysis"
        )

        print(
            "\n[STEP 3C] SQL Risk Analysis"
        )

        sql_risk = analyze_sql_risk(
            sql_action
        )

        print(
            sql_risk
        )

        write_audit_log(
            f"SQL RISK: {sql_risk}"
        )

        write_audit_log(
            "STEP 3C COMPLETED - SQL Risk Analysis"
        )

        # =================================================
        # STEP 3D - SQL VALIDATION
        # =================================================

        write_audit_log(
            "STEP 3D STARTED - SQL Validation"
        )

        print(
            "\n[STEP 3D] SQL Validation"
        )

        if sql_action[
            "action_type"
        ] == "NO_ACTION":

            validation_result = {
                "approved": False,
                "reason": "No SQL Action Required"
            }

        else:

            validation_result = validate_sql_action(
                sql_action
            )

        print(
            validation_result
        )

        write_audit_log(
            f"SQL VALIDATION: {validation_result}"
        )

        write_audit_log(
            "STEP 3D COMPLETED - SQL Validation"
        )

        # =================================================
        # STEP 4 - GOVERNANCE REVIEW
        # =================================================

        write_audit_log(
            "STEP 4 STARTED - Governance Review"
        )

        print(
            "\n[STEP 4] Governance Review"
        )

        governance_required = (
            agent_result[
                "risk"
            ][
                "approval_required"
            ]
            or
            sql_risk[
                "approval_required"
            ]
        )

        if governance_required:

            governance_context = (
                f"Severity: {agent_result['risk']['severity']} | "
                f"{agent_result['recommendation']['recommendation']}"
            )

            approval_request = create_governance_request(
                governance_context
            )

            save_action(
                "GOVERNANCE_REQUEST",
                "GOVERNANCE ENGINE",
                "CREATED",
                approval_request[
                    "request_id"
                ]
            )

            write_audit_log(
                f"GOVERNANCE REQUEST ID: {approval_request['request_id']}"
            )

        else:

            print(
                "No governance approval required."
            )

            write_audit_log(
                "GOVERNANCE REVIEW SKIPPED - NO APPROVAL REQUIRED"
            )

        write_audit_log(
            "STEP 4 COMPLETED - Governance Review"
        )

        # =================================================
        # STEP 4A - SQL EXECUTION
        # =================================================

        write_audit_log(
            "STEP 4A STARTED - SQL Execution"
        )

        print(
            "\n[STEP 4A] SQL Execution"
        )

        if sql_action[
            "action_type"
        ] == "NO_ACTION":

            execution_result = {
                "status": "SKIPPED",
                "reason": "No SQL Action Required"
            }

        elif (
            validation_result[
                "approved"
            ]
            and
            not sql_risk[
                "approval_required"
            ]
        ):

            execution_result = execute_sql_action(
                sql_action
            )

        else:

            execution_result = {
                "status": "BLOCKED",
                "reason": (
                    "Approval Required"
                    if sql_risk[
                        "approval_required"
                    ]
                    else validation_result[
                        "reason"
                    ]
                )
            }

        print(
            execution_result
        )

        save_action(
            "SQL_EXECUTION",
            "SQL EXECUTOR",
            execution_result[
                "status"
            ],
            str(
                execution_result
            )
        )

        write_audit_log(
            f"SQL EXECUTION: {execution_result}"
        )

        write_audit_log(
            "STEP 4A COMPLETED - SQL Execution"
        )

        # =================================================
        # STEP 4B - EXECUTION VERIFICATION
        # =================================================

        write_audit_log(
            "STEP 4B STARTED - Execution Verification"
        )

        print(
            "\n[STEP 4B] Execution Verification"
        )

        verification_result = verify_execution(
            monitoring_result,
            execution_result
        )

        print(
            verification_result
        )

        write_audit_log(
            f"VERIFICATION RESULT: {verification_result}"
        )

        write_audit_log(
            "STEP 4B COMPLETED - Execution Verification"
        )

        # =================================================
        # STEP 4C - REMEDIATION EXECUTION
        # =================================================

        write_audit_log(
            "STEP 4C STARTED - Remediation Execution"
        )

        print(
            "\n[STEP 4C] Remediation Execution"
        )

        if (
            agent_result[
                "risk"
            ][
                "severity"
            ] == "LOW"
            or
            sql_action[
                "action_type"
            ] == "NO_ACTION"
        ):

            remediation_result = {
                "status": "SKIPPED",
                "reason": "System Healthy"
            }

        else:

            remediation_result = execute_remediation(
                agent_result[
                    "recommendation"
                ]
            )

        print(
            remediation_result
        )

        save_action(
            "REMEDIATION",
            "REMEDIATION ENGINE",
            remediation_result[
                "status"
            ],
            str(
                remediation_result
            )
        )

        write_audit_log(
            f"REMEDIATION RESULT: {remediation_result}"
        )

        write_audit_log(
            "STEP 4C COMPLETED - Remediation Execution"
        )

        # =================================================
        # STEP 5 - REPORT GENERATION
        # =================================================

        write_audit_log(
            "STEP 5 STARTED - Report Generation"
        )

        print(
            "\n[STEP 5] Generate RCA Report"
        )

        report_file = save_report(
            monitoring_result[
                "overall_status"
            ],
            monitoring_result[
                "incident_summary"
            ],
            ai_result[
                "analysis"
            ]
        )

        write_audit_log(
            "STEP 5 COMPLETED - Report Generation"
        )

        write_audit_log(
            f"REPORT FILE CREATED: {report_file}"
        )

        # =================================================
        # STEP 6 - INCIDENT REPOSITORY
        # =================================================

        write_audit_log(
            "STEP 6 STARTED - Incident Repository"
        )

        print(
            "\n[STEP 6] Save Incident To Repository"
        )

        save_incident(
            monitoring_result[
                "overall_status"
            ],
            monitoring_result[
                "incident_summary"
            ],
            ai_result[
                "analysis"
            ],
            report_file
        )

        write_audit_log(
            "STEP 6 COMPLETED - Incident Repository"
        )

        # =================================================
        # STEP 7 - NOTIFICATIONS
        # =================================================

        write_audit_log(
            "STEP 7 STARTED - Notifications"
        )

        print(
            "\n[STEP 7] Send Notifications"
        )

        if (
            notification_route[
                "send_email"
            ]
            or
            notification_route[
                "send_teams"
            ]
        ):

            run_notifications(
                monitoring_result[
                    "overall_status"
                ],
                monitoring_result[
                    "incident_summary"
                ]
            )

            save_action(
                "NOTIFICATION",
                "NOTIFICATION ENGINE",
                "SENT",
                str(
                    notification_route
                )
            )

        else:

            print(
                "Notification not required."
            )

            save_action(
                "NOTIFICATION",
                "NOTIFICATION ENGINE",
                "SKIPPED",
                "Notification not required"
            )

        write_audit_log(
            "STEP 7 COMPLETED - Notifications"
        )

        # =================================================
        # STEP 8 - SAVE REPORT
        # =================================================

        write_audit_log(
            "STEP 8 STARTED - Save Report"
        )

        print(
            "\n[STEP 8] Save Incident Report"
        )

        print(
            f"Report saved successfully: {report_file}"
        )

        write_audit_log(
            "STEP 8 COMPLETED - Save Report"
        )

        # =================================================
        # WORKFLOW COMPLETED
        # =================================================

        write_audit_log(
            "WORKFLOW COMPLETED"
        )

        print("\n========================================")
        print(" MCP WORKFLOW COMPLETED ")
        print("========================================\n")

        return {
            "status": "SUCCESS",
            "overall_status": monitoring_result[
                "overall_status"
            ],
            "report_file": report_file,
            "approval_request": approval_request,
            "sql_action": sql_action,
            "sql_risk": sql_risk,
            "validation_result": validation_result,
            "execution_result": execution_result,
            "verification_result": verification_result,
            "remediation_result": remediation_result
        }

    except Exception as error:

        return handle_error(
            "WORKFLOW MANAGER",
            error
        )


# =========================================================
# GET WORKFLOW STEPS
# =========================================================

def get_workflow_steps():
    """
    Return workflow steps.
    """

    return WORKFLOW_STEPS


# =========================================================
# WORKFLOW SUMMARY
# =========================================================

def workflow_summary():
    """
    Display workflow summary.
    """

    print("\n========================================")
    print(" WORKFLOW SUMMARY ")
    print("========================================\n")

    print(
        f"Total Workflow Steps : {len(WORKFLOW_STEPS)}"
    )

    print(
        "Workflow Status      : Active"
    )

    print(
        "Environment Check    : Enabled"
    )

    print(
        "Governance Layer     : Enabled"
    )


# =========================================================
# TEST EXECUTION
# =========================================================

if __name__ == "__main__":

    display_workflow_steps()

    execute_workflow()

    workflow_summary()